image: google/cloud-sdk:alpine

deploy_production:
  stage: deploy
  environment: Production
  only:
  - main
  script:
  - echo $SERVICE_ACCOUNT > /tmp/gcloud-service-key.json # Google Cloud service accounts
  - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
  - gcloud config set project $PROJECT_ID
  - gcloud builds submit . --config=cloudbuild.yaml --gcs-log-dir=gs://foodash-cloudbuilds-logs

deploy_staging:
  stage: deploy
  environment: Staging
  only:
  - staging
  script:
    - echo $SERVICE_ACCOUNT > /tmp/gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud builds submit . --config=staging-cloudbuild.yaml --gcs-log-dir=gs://foodash-cloudbuilds-logs


after_script:
- rm /tmp/gcloud-service-key.json