trigger: 
  - main
  
pool: test-pool

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.10.0'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
    workingDirectory: $(Build.SourcesDirectory)/src

  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'src/dist'
      api_location: ''
      output_location: ''
    env:
      azure_static_web_apps_api_token: $(DeploymentToken)